<a href="https://colab.research.google.com/github/sasikiran-b/git-python-project/blob/main/simple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import data
import pandas as pd
data = pd.read_csv('Salary_Data_SLR.csv')
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
#Step - 2 : Separate both i/p & o/p
X = data.iloc[:,0].values
X = X.reshape(-1,1)
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [4]:
Y = data.iloc[:,-1].values
print(Y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [5]:
#Step - 3 : Splitting the data into train and test.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)
print(X_train)

[[ 2.2]
 [ 4.9]
 [ 3.2]
 [ 9.6]
 [ 6. ]
 [ 4. ]
 [ 8.2]
 [ 7.9]
 [ 4. ]
 [ 3.9]
 [ 8.7]
 [ 7.1]
 [10.3]
 [ 2.9]
 [ 4.1]
 [ 5.1]
 [ 2. ]
 [ 3. ]
 [ 6.8]
 [ 5.9]
 [10.5]
 [ 4.5]
 [ 5.3]
 [ 3.2]]


In [6]:
#Step - 4 : Model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression().fit(X_train, Y_train)
print(regressor.intercept_,
regressor.coef_)

24038.666196420374 [9753.51096238]


In [7]:
regressor.predict([[2]])

array([43545.68812119])

In [8]:
regressor.predict(X_test)

array([ 36718.23044752, 111820.26485788,  38668.93264   ,  60126.65675724,
        34767.52825504, 116697.02033908])

In [9]:
Y_test

array([ 46205., 105582.,  37731.,  57189.,  39343., 116969.])